name: CI
on:
#   schedule:
#     - cron: '0/5 * * * *'
  issues:
    types: [ opened, edited, deleted, closed, labeled, unlabeled ]
  issue_comment:
    types: [ created, edited, deleted ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - name: Fetch issues and comments to json files
        run: |
          bash ./build.sh
      - name: Commit json files
        run: |
          git add --force ./asset/json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff-index --quiet HEAD || git commit -m "Auto updating json files"
      - name: Push json files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          force: true
