name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Fetch issues and comments to json files
        run: |
          bash ./build.sh
      - name: Commit json files
        run: |
          echo "Hello from $GITHUB_REPOSITORY $GITHUB_USER"
