name: CI
on:
  push:
    branches-ignore:
      - master
  pull_request_target:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          BRANCH-TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Hello World"


